### ISSUE TITLE
Deprecation of API

### ISSUE THREAD

**Issue by alireza-rezaee** [ghost1372/CoronaVirusPandemic#1]
<div dir="rtl">
سلام.
<br>
متاسفانه
API در حال استفاده،
 توسط توسعه دهنده منسوخ شده است.
</div>
<pre>
using (HttpClient client = new HttpClient())
{
    string requestUri = "https://corona.lmao.ninja/countries?sort=cases";
    HttpResponseMessage apiResponse = await client.GetAsync(requestUri);
    string jsonResponse = await apiResponse.Content.ReadAsStringAsync();
</pre>
See: <a href="https://corona.lmao.ninja/countries?sort=cases">https://corona.lmao.ninja/countries?sort=cases</a>
<br>
<code>message: This endpoint has been deprecated. Use /v3/covid-19/countries instead.</code>
<br>
<code>docs: https://corona.lmao.ninja/docs/</code>

**Comment by ghost1372** [comment]
سلام ممنون بابت گزارش بزودی اصلاح میکنم
